import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nautev — Make things simple",
  description: "Generated by create next app",
};

type Props = {
  children: any
}

export default function Layout(props: Props) {
    return (
      <div>
        {props.children}
      </div>
    );
}